"""运单列表查询参数（列表 / 导出共用）。"""

from __future__ import annotations

from typing import Annotated

from fastapi import Depends, Query


def get_shipment_list_filters(
    search: str | None = None,
    tracking_search: str | None = Query(None, alias="trackingSearch"),
    shipment_nos: list[str] | None = Query(None, alias="shipmentNos"),
    status_code: str | None = Query(None, alias="statusCode"),
    exception_code: str | None = Query(None, alias="exceptionCode"),
    has_exception: bool | None = Query(None, alias="hasException"),
    customer: str | None = None,
    vip_only: bool | None = Query(None, alias="vipOnly"),
    carrier_code: str | None = Query(None, alias="carrierCode"),
    country_code: str | None = Query(None, alias="countryCode"),
    channel_code: str | None = Query(None, alias="channelCode"),
    channel_name_zh: str | None = Query(None, alias="channelNameZh"),
    channel_category: str | None = Query(None, alias="channelCategory"),
    vessel_voyage: str | None = Query(None, alias="vesselVoyage"),
    internal_freshness: str | None = Query(None, alias="internalFreshness"),
    carrier_freshness: str | None = Query(None, alias="carrierFreshness"),
    carrier_ahead_of_internal: bool | None = Query(None, alias="carrierAheadOfInternal"),
    pending_tracking_time_review: bool | None = Query(
        None, alias="pendingTrackingTimeReview"
    ),
    min_stale_days: int | None = Query(None, alias="minStaleDays"),
    no_tracking: bool | None = Query(None, alias="noTracking"),
    no_zipcode: bool | None = Query(None, alias="noZipcode"),
    group_id: str | None = Query(None, alias="groupId"),
    group_no: str | None = Query(None, alias="groupNo"),
    rule_type: str | None = Query(None, alias="ruleType"),
    has_rule: bool | None = Query(None, alias="hasRule"),
    has_group: bool | None = Query(None, alias="hasGroup"),
    time_field: str | None = Query(None, alias="timeField"),
    time_from: str | None = Query(None, alias="timeFrom"),
    time_to: str | None = Query(None, alias="timeTo"),
    etd_from: str | None = Query(None, alias="etdFrom"),
    etd_to: str | None = Query(None, alias="etdTo"),
    atd_from: str | None = Query(None, alias="atdFrom"),
    atd_to: str | None = Query(None, alias="atdTo"),
    eta_from: str | None = Query(None, alias="etaFrom"),
    eta_to: str | None = Query(None, alias="etaTo"),
    ata_from: str | None = Query(None, alias="ataFrom"),
    ata_to: str | None = Query(None, alias="ataTo"),
    expected_delivery_from: str | None = Query(None, alias="expectedDeliveryFrom"),
    expected_delivery_to: str | None = Query(None, alias="expectedDeliveryTo"),
    delivered_from: str | None = Query(None, alias="deliveredFrom"),
    delivered_to: str | None = Query(None, alias="deliveredTo"),
    created_from: str | None = Query(None, alias="createdFrom"),
    created_to: str | None = Query(None, alias="createdTo"),
    updated_from: str | None = Query(None, alias="updatedFrom"),
    updated_to: str | None = Query(None, alias="updatedTo"),
    customer_no: str | None = Query(None, alias="customerNo"),
    destination_port_code: str | None = Query(None, alias="destinationPortCode"),
    address_keyword: str | None = Query(None, alias="addressKeyword"),
    missing_etd: bool | None = Query(None, alias="missingEtd"),
    missing_atd: bool | None = Query(None, alias="missingAtd"),
    missing_eta: bool | None = Query(None, alias="missingEta"),
    missing_ata: bool | None = Query(None, alias="missingAta"),
    missing_expected_delivery: bool | None = Query(None, alias="missingExpectedDelivery"),
    missing_delivered: bool | None = Query(None, alias="missingDelivered"),
    not_delivered: bool | None = Query(None, alias="notDelivered"),
    has_ata: bool | None = Query(None, alias="hasAta"),
    delivery_risk: str | None = Query(None, alias="deliveryRisk"),
    sort_by: str | None = Query(None, alias="sortBy"),
    sort_order: str | None = Query(None, alias="sortOrder"),
) -> dict:
    return {
        "search": search,
        "tracking_search": tracking_search,
        "shipment_nos": shipment_nos,
        "status_code": status_code,
        "exception_code": exception_code,
        "has_exception": has_exception,
        "customer": customer,
        "vip_only": vip_only,
        "carrier_code": carrier_code,
        "country_code": country_code,
        "channel_code": channel_code,
        "channel_name_zh": channel_name_zh,
        "channel_category": channel_category,
        "vessel_voyage": vessel_voyage,
        "internal_freshness": internal_freshness,
        "carrier_freshness": carrier_freshness,
        "carrier_ahead_of_internal": carrier_ahead_of_internal,
        "pending_tracking_time_review": pending_tracking_time_review,
        "min_stale_days": min_stale_days,
        "no_tracking": no_tracking,
        "no_zipcode": no_zipcode,
        "group_id": group_id,
        "group_no": group_no,
        "rule_type": rule_type,
        "has_rule": has_rule,
        "has_group": has_group,
        "time_field": time_field,
        "time_from": time_from,
        "time_to": time_to,
        "etd_from": etd_from,
        "etd_to": etd_to,
        "atd_from": atd_from,
        "atd_to": atd_to,
        "eta_from": eta_from,
        "eta_to": eta_to,
        "ata_from": ata_from,
        "ata_to": ata_to,
        "expected_delivery_from": expected_delivery_from,
        "expected_delivery_to": expected_delivery_to,
        "delivered_from": delivered_from,
        "delivered_to": delivered_to,
        "created_from": created_from,
        "created_to": created_to,
        "updated_from": updated_from,
        "updated_to": updated_to,
        "customer_no": customer_no,
        "destination_port_code": destination_port_code,
        "address_keyword": address_keyword,
        "missing_etd": missing_etd,
        "missing_atd": missing_atd,
        "missing_eta": missing_eta,
        "missing_ata": missing_ata,
        "missing_expected_delivery": missing_expected_delivery,
        "missing_delivered": missing_delivered,
        "not_delivered": not_delivered,
        "has_ata": has_ata,
        "delivery_risk": delivery_risk,
        "sort_by": sort_by,
        "sort_order": sort_order,
    }


ShipmentListFilters = Annotated[dict, Depends(get_shipment_list_filters)]
